class Img{
  static const imgAdr = 'assets/images/';
  static const iconAdr = 'assets/icons/';
  static const String splashImg = '${imgAdr}splashImg.png';
  static const String logoImg = '${imgAdr}logo.png';
  static const String bottomBanner = '${imgAdr}loginBottomBanner.svg';
  static const String bookImg = '${imgAdr}bookImg.png';
  static const String homeIcon = '${iconAdr}home.png';
  static const String translationIcon = '${iconAdr}translations.png';
  static const String paymentIcon = '${iconAdr}payment.png';
  static const String newsLetterIcon = '${iconAdr}translations.png';
  static const String profileIcon = '${iconAdr}profile.png';
  static const String notificationIcon = '${iconAdr}notification.png';
  static const String settingIcon = '${iconAdr}settings.png';
  static const String aboutUsIcon = '${iconAdr}aboutUs.png';
  static const String contactUsIcon = '${iconAdr}contactUs.png';
  static const String logoutIcon = '${iconAdr}logout.png';
  static const String menuIcon = '${iconAdr}menu.png';
  static const String notificationOutlineIcon = '${iconAdr}notificationOutline.png';
  static const String searchIcon = '${iconAdr}search.png';
  static const String accountIcon = '${iconAdr}account.png';
  static const String notificationBlueOutIcon = '${iconAdr}notificationBlue.png';
  static const String passwordLockBlueIcon = '${iconAdr}passwordLock.png';
  static const String worldBlueIcon = '${iconAdr}world.png';
  static const String bankBlueIcon = '${iconAdr}bank.png';
  static const String shieldBlueIcon = '${iconAdr}shield.png';
  static const String fileBlueIcon = '${iconAdr}file.png';
  static const String amountReceiveIcon = '${iconAdr}amountReceive.png';
}